name=A02YYUW_Library
version=1.0.0
author=Alfan Risqi wahyudi <aminwayering123>
maintainer=Alfan Risqi Wahyudi <aminwayering123@gmail.com>
sentences=A library for interfacing with the A02YYUW ultrasonic sensor.
paragraph=The A02YYUW library allows you to measure distance using the A02YYUW ultrasonic sensor via UART Communication. It provides an easy-to-use interface to read distance data. 
category=Sensors
url=https://github.com/alfan459/A02YYUW-Sensor-Library
architectures=*
